// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwrdqeexjisdxuwijmcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3cmRxZWV4amlzZHh1d2lqbWN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MDIyMzksImV4cCI6MjA2NTk3ODIzOX0.h0ZU2gGmB-DneBec12_qHzpzixssG0wOMVZ6F-u3iVI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);